export enum MUTATION_TYPE {
  ADD_PAGE = "ADD_PAGE",
  REMOVE_PAGE = "REMOVE_PAGE",
  ADD_COMPONENT = "ADD_COMPONENT",
  REMOVE_COMPONENT = "REMOVE_COMPONENT",
  UNDO = "UNDO",
  REDO = "REDO",
  INIT = "INIT",
}
